### ISSUE TITLE
[FAILED] addMany Missing helper: "fill"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/create-shield-study#1]
I notice that when running <kbd>$ ./create-shield-study blah</kbd> locally, I get the following error (but it also seems to correctly(?) build the project files locally):

> #### _[FAILED] addMany Missing helper: "fill"_

### Steps to reproduce:

```sh
$ git rev-parse --short HEAD # ecf131b

$ ./create-shield-study peter-is-no-bueno
? Shield (or Pioneer) shield
? inform Strategy and Insights about your project Yes
? choose all starting libraries shield-study-addon-utils
[FAILED] addMany Missing helper: "fill"
[FAILED] info Aborted due to previous action failure

$ tree peter-is-no-bueno
peter-is-no-bueno
└── shield-study
    ├── LICENSE
    ├── README.md
    ├── docs
    │   ├── DEV.md
    │   ├── TELEMETRY.md
    │   ├── TESTPLAN.md
    │   └── WINDOWS_SETUP.md
    ├── karma.conf.js
    ├── package-lock.json
    ├── package.json
    ├── src
    │   ├── background.js
    │   └── feature.js
    └── web-ext-config.js

3 directories, 12 files
```

**Comment by amwmedia** [comment]
This appears to be caused by what I assume is [a placeholder value](https://github.com/mozilla/create-shield-study/blob/95f5c5f2183899cc165683b3626bc55778152023/templates/shield-study/src/manifest.json#L8) of "{{fill in your thing}}" which handlebars is interpreting as using a `fill` helper, which it cannot find.
